Repository munich-quantum-toolkit/qcec, pull requests merged in 2022-08, with the labels that each got.

#112 💚 Repair CI
  setup.py
Labels: bug, continuous integration

#116 🚸 better Python bindings exceptions
  mqt/qcec/bindings.cpp
Labels: usability

#117 🚸♻️ improved `verify` functions
  mqt/qcec/__init__.py
  mqt/qcec/bindings.cpp
  mqt/qcec/verify.py
  mqt/qcec/verify_compilation_flow.py
  test/python/test_verify.py
  test/python/test_verify_compilation.py
Labels: usability

#123 🔧 Update dependabot config
  .github/dependabot.yml
Labels: enhancement, dependencies

#124 🐍🔧 Specify Metadata via PEP 621
  MANIFEST.in
  mqt/qcec/verify_compilation_flow.py
  noxfile.py
  pyproject.toml
  setup.py
  test/python/test.py
Labels: enhancement, python, packaging

#125 🔧 Add Issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.md
Labels: enhancement

#127 Updated docs with the JETCAS Publication.
  README.md
  docs/source/EquivalenceChecking.rst
  docs/source/Publications.rst
  docs/source/refs.bib
Labels: documentation

#130 🐛 Fix `cpp-linter`
  .github/workflows/cpp-linter.yml
  test/legacy/test_general.cpp
Labels: bug, continuous integration
