Repository munich-quantum-toolkit/qcec, pull requests merged in 2023-11, with the labels that each got.

#327 adapt to new qiskit version.
  pyproject.toml
  src/mqt/qcec/parameterized.py
Labels: dependencies, python

#328 ⬆️ update `scikit-build-core`
  .pre-commit-config.yaml
  noxfile.py
  pyproject.toml
  test/python/constraints.txt
Labels: dependencies, python, packaging

#329 🚨 small ruff updates
  docs/source/conf.py
  pyproject.toml
  src/mqt/qcec/compilation_flow_profiles.py
  test/python/test_compilation_flow_profiles.py
  test/python/test_symbolic.py
  test/python/test_verify_compilation.py
Labels: code quality

#330 📝 added project acknowledgements
  README.md
  docs/source/_static/custom.css
  docs/source/_static/erc_dark.svg
  docs/source/_static/erc_light.svg
  docs/source/_static/logo-bavaria.svg
  docs/source/_static/logo-mqv.svg
  docs/source/_static/tum_dark.svg
  docs/source/_static/tum_light.svg
  docs/source/_templates/page.html
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation

#332 🔥 remove check-sdist from pre-commit
  .pre-commit-config.yaml
Labels: usability, continuous integration
