Repository munich-quantum-toolkit/qcec, pull requests merged in 2024-05, with the labels that each got.

#392 🍱 MQT Branding
  README.md
  docs/source/_static/erc_dark.svg
  docs/source/_static/erc_light.svg
  docs/source/_static/logo-bavaria.svg
  docs/source/_static/logo-mqv.svg
  docs/source/_static/tum_dark.svg
  docs/source/_static/tum_light.svg
  docs/source/_templates/page.html
Labels: documentation

#394 :bug: Fix strip idle qubits
  docs/source/library/EquivalenceCheckingManager.rst
  include/Configuration.hpp
  include/EquivalenceCheckingManager.hpp
  include/checker/dd/applicationscheme/GateCostApplicationScheme.hpp
  noxfile.py
  pyproject.toml
  src/Configuration.cpp
  src/EquivalenceCheckingManager.cpp
  src/checker/zx/ZXChecker.cpp
  src/mqt/qcec/compilation_flow_profiles.py
  src/mqt/qcec/configuration.py
  src/mqt/qcec/profiles/qiskit_O0_noancilla.profile
  src/mqt/qcec/profiles/qiskit_O0_recursion.profile
  src/mqt/qcec/profiles/qiskit_O0_v-chain.profile
  src/mqt/qcec/profiles/qiskit_O1_noancilla.profile
  src/mqt/qcec/profiles/qiskit_O1_recursion.profile
  src/mqt/qcec/profiles/qiskit_O1_v-chain.profile
  src/mqt/qcec/profiles/qiskit_O2_noancilla.profile
  src/mqt/qcec/profiles/qiskit_O2_recursion.profile
  src/mqt/qcec/profiles/qiskit_O2_v-chain.profile
  src/mqt/qcec/profiles/qiskit_O3_noancilla.profile
  src/mqt/qcec/profiles/qiskit_O3_recursion.profile
  src/mqt/qcec/profiles/qiskit_O3_v-chain.profile
  src/mqt/qcec/pyqcec.pyi
  src/python/bindings.cpp
  test/legacy/test_general.cpp
  test/python/test_compilation_flow_profiles.py
  test/test_equality.cpp
Labels: c++, fix

#397 📦 smaller Python wheels
  pyproject.toml
  src/python/CMakeLists.txt
Labels: python, packaging

#399 ⬆️ update black version in blacken-docs
  .pre-commit-config.yaml
Labels: dependencies, continuous integration

#400 ⬆️ update to `mqt-workflows==1.0.1`
  .github/codecov.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: dependencies, github_actions, continuous integration
